#!/usr/bin/env groovy

@Library('apm@current') _

pipeline {
  agent { label 'linux && immutable' }
  environment {
    REPO = 'ecs-logging-nodejs'
    BASE_DIR = "src/go.elastic.co/apm/${env.REPO}"
    NOTIFY_TO = credentials('notify-to')
    JOB_GCS_BUCKET = credentials('gcs-bucket')
  }
  options {
    timeout(time: 1, unit: 'HOURS')
    buildDiscarder(logRotator(numToKeepStr: '20', artifactNumToKeepStr: '20', daysToKeepStr: '30'))
    timestamps()
    ansiColor('xterm')
    disableResume()
    durabilityHint('PERFORMANCE_OPTIMIZED')
    rateLimitBuilds(throttle: [count: 60, durationName: 'hour', userBoost: true])
    quietPeriod(10)
  }
  triggers {
    issueCommentTrigger("${obltGitHubComments()}")
  }
  stages {
    stage('Checkout') {
      options { skipDefaultCheckout() }
      steps {
        pipelineManager([ cancelPreviousRunningBuilds: [ when: 'PR' ] ])
        deleteDir()
        gitCheckout(basedir: "${BASE_DIR}", githubNotifyFirstTimeContributor: true)
        stash(allowEmpty: true, name: 'source', useDefaultExcludes: false)
      }
    }
    stage('Compatibility matrix'){
      options { skipDefaultCheckout() }
      matrix {
        agent { label 'linux && immutable' }
        axes {
          axis {
            name 'NODE_VERSION'
            values (
              '10',
              '12',
              '14',
              '16',
              '17'
            )
          }
        }
        stages {
          stage('Test - Node.js') {
            steps {
              withGithubNotify(context: "Test - Node.js v${NODE_VERSION}") {
                deleteDir()
                unstash 'source'
                dir("${BASE_DIR}"){
                  docker.image("node:${NODE_VERSION}").inside("-e HOME=${WORKSPACE}/${BASE_DIR}") {
                    sh(label: 'Install dependencies', script: '.ci/run-install.sh')
                    sh(label: 'Run tests', script: '.ci/run-test.sh')
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  post {
    cleanup {
      notifyBuildResult()
    }
  }
}
